# SMTP server
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    hostname: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

networks:
  default: 
    name: docker-default
