services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: my-rabbit
    labels:
      NAME: "rabbitmq1"
    # volumes:
    #   - ./.docker/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #   - ./.docker/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #   - ./.docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #   - ./.docker/rabbitmq/logs:/var/log/rabbitmq/log
    
    # OR Just the directories themselves
    #   - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #   - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/

    # environment:
    #   RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    #   RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    #   RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    #   RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5 

networks:
  default: 
    name: docker-default
