services:
  postgres:
      image: "postgres"
      container_name: postgres
      hostname: "postgres-host"
      volumes:
          - ./.docker/postgres:/var/lib/postgresql/data"
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "admin@1234"
          POSTGRES_DB: "PGDatabase"
          ACCEPT_EULA: "Y"

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      depends_on: 
          - postgres
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
          PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
          - ./.docker/pgadmin:/root/.pgadmin

      ports:
          - "${PGADMIN_PORT:-5050}:80"
      restart: unless-stopped
