version: "3.7"
services:
    # run azurite and expose the relevant ports
    azurite:
        container_name: azurite
        hostname: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - 10000:10000
            - 10001:10001
            - 10002:10002
        restart: unless-stopped
        volumes:
            - ./.docker/azurite:/data

networks:
  default: 
    name: docker-default
