services:
  # can connect to sql server from outside container
  # using SQL TOOL server: localhost, user:sa and password as below
  # or sqlcmd -S localhost,1433 -U sa -P "docker_sql@123"
  mongo:
    image: "mongo"
    container_name: mongo
    hostname: mongo
    environment:
      #MONGODB_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017-27019:27017-27019"
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./.docker/mongodb:/data/db
    restart: unless-stopped
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

networks:
  default: 
    name: docker-default
